import os
from typing import Dict, Any, List

def get_demo_cases() -> List[Dict[str, Any]]:
    return [
        {
            "id": "clean_record",
            "title": "1. Clean & Valid Record (Concordant)",
            "badge": "VALID",
            "badge_color": "green",
            "description": "Standard Jamabandi extract with 100% field concordance with the district land registry.",
            "sample_file": "demo_1_clean_record.png",
            "khasra": "245/2",
            "khata": "104",
            "owner": "Ramesh Kumar",
            "father": "Suresh Chandra",
            "village": "Rampur",
            "tehsil": "Sadar",
            "district": "Lucknow",
            "area_ha": 1.05,
            "ref_area_ha": 1.05,
            "expected_status": "VALID",
            "expected_score": 97.8,
            "highlight": "Zero discrepancies detected. High OCR clarity. Eligible for immediate automated revenue endorsement."
        },
        {
            "id": "area_mismatch",
            "title": "2. Area Mismatch Flag (+0.15 ha Delta)",
            "badge": "REVIEW_REQUIRED",
            "badge_color": "amber",
            "description": "Digitized land deed declares 1.20 ha, whereas authoritative registry records 1.05 ha.",
            "sample_file": "demo_2_area_mismatch.png",
            "khasra": "245/2",
            "khata": "104",
            "owner": "Ramesh Kumar",
            "father": "Suresh Chandra",
            "village": "Rampur",
            "tehsil": "Sadar",
            "district": "Lucknow",
            "area_ha": 1.20,
            "ref_area_ha": 1.05,
            "expected_status": "REVIEW_REQUIRED",
            "expected_score": 78.5,
            "highlight": "Area variance of +14.3% flagged. Automated recommendation for ground truthing by Revenue Inspector."
        },
        {
            "id": "owner_variation",
            "title": "3. Owner Name Variation (Fuzzy 94% Match)",
            "badge": "REVIEW_REQUIRED",
            "badge_color": "amber",
            "description": "OCR extracted 'Ramesh Kumar', official registry has 'Ramesh Kr.' with identical parentage.",
            "sample_file": "demo_3_owner_variation.png",
            "khasra": "246/1",
            "khata": "112",
            "owner": "Ramesh Kumar",
            "father": "Mahesh Chandra",
            "village": "Rampur",
            "tehsil": "Sadar",
            "district": "Lucknow",
            "area_ha": 0.88,
            "ref_area_ha": 0.88,
            "expected_status": "REVIEW_REQUIRED",
            "expected_score": 86.2,
            "highlight": "RapidFuzz token-sort similarity score of 94%. Recommended identity check against Aadhaar / Voter ID."
        },
        {
            "id": "khasra_mismatch",
            "title": "4. Khasra Mismatch (Plot Identity Conflict)",
            "badge": "HIGH_RISK",
            "badge_color": "red",
            "description": "Applicant document cites Khasra 245/7 claiming title over registered parcel 245/2.",
            "sample_file": "demo_4_khasra_mismatch.png",
            "khasra": "245/7",
            "khata": "104",
            "owner": "Ramesh Kumar",
            "father": "Suresh Chandra",
            "village": "Rampur",
            "tehsil": "Sadar",
            "district": "Lucknow",
            "area_ha": 1.05,
            "ref_area_ha": 1.05,
            "expected_status": "HIGH_RISK",
            "expected_score": 48.0,
            "highlight": "Severe parcel mismatch. Prevents potential fraudulent double-claim or boundary encroachment."
        },
        {
            "id": "mutation_issue",
            "title": "5. Active Legal Encumbrance & Succession Dispute",
            "badge": "HIGH_RISK",
            "badge_color": "red",
            "description": "Parcel 312/1 has an active civil court injunction and contested inheritance objection.",
            "sample_file": "demo_5_mutation_issue.png",
            "khasra": "312/1",
            "khata": "145",
            "owner": "Vikram Singh",
            "father": "Ranveer Singh",
            "village": "Rampur",
            "tehsil": "Sadar",
            "district": "Lucknow",
            "area_ha": 2.10,
            "ref_area_ha": 2.10,
            "expected_status": "HIGH_RISK",
            "expected_score": 52.0,
            "highlight": "Active legal stay detected in registry. Halts unauthorized registration until Tehsildar decree."
        },
        {
            "id": "degraded_scan",
            "title": "6. Degraded Scan / Low OCR Confidence",
            "badge": "REVIEW_REQUIRED",
            "badge_color": "amber",
            "description": "Aged, noisy physical archive scan with faded ink triggering adaptive OCR thresholding.",
            "sample_file": "demo_6_degraded_scan.png",
            "khasra": "245/2",
            "khata": "104",
            "owner": "Ramesh Kumar",
            "father": "Suresh Chandra",
            "village": "Rampur",
            "tehsil": "Sadar",
            "district": "Lucknow",
            "area_ha": 1.05,
            "ref_area_ha": 1.05,
            "expected_status": "REVIEW_REQUIRED",
            "expected_score": 74.0,
            "highlight": "Character confidence dropped below 65%. Officer guided to verify smudged numerical fields."
        },
        {
            "id": "multiple_anomalies",
            "title": "7. Multiple Critical Anomalies (Severe Risk)",
            "badge": "HIGH_RISK",
            "badge_color": "red",
            "description": "Document shows inflated area (+123%), owner divergence, and active boundary litigation.",
            "sample_file": "demo_7_multiple_anomalies.png",
            "khasra": "245/7",
            "khata": "118",
            "owner": "Dinesh Kumar Verma",
            "father": "Kailash Chandra Verma",
            "village": "Rampur",
            "tehsil": "Sadar",
            "district": "Lucknow",
            "area_ha": 1.45,
            "ref_area_ha": 0.65,
            "expected_status": "HIGH_RISK",
            "expected_score": 34.5,
            "highlight": "Cumulative threat score. Automatic referral to District Anti-Fraud Land Cell."
        }
    ]
